#' top_tr_tabulation
#'
#' This is the step6 function of the TENETR package.
#' This function takes the identified hyper and hypomethylated probes
#' from step2 get_diffmeth_regions function and calculates a zscore comparing
#' the mean expression of each gene in groups that are hyper/hypomethylated for
#' each probe, according to hypermeth and hypometh and those that are not, and permutates this across all
#' hyper/hypomethylated probes
#'
#'
#' @param TENET_directory Set a path to the directory that contains step5 results from the optimize_links function. This function will also create a new step6 folder there containing the results.
#' @param hypermeth_Gplus_analysis Set to TRUE/FALSE depending on if you want to calculate the top_trs for hypermeth probes with G+ links.
#' @param hypermeth_Gminus_analysis Set to TRUE/FALSE depending on if you want to calculate the top_trs for hypermeth probes with G- links.
#' @param hypometh_Gplus_analysis Set to TRUE/FALSE depending on if you want to calculate the top_trs for hypometh probes with G+ links.
#' @param hypometh_Gminus_analysis Set to TRUE/FALSE depending on if you want to calculate the top_trs for hypometh probes with G- links.
#' @return Currently returns tab-delimited "_freq.txt" files that include all genes, or annotated TFs only, organized by decreasing number of linked probes of the given analysis type.
#' @export

top_tr_tabulation <- function(
  TENET_directory,
  hypermeth_Gplus_analysis,
  hypermeth_Gminus_analysis,
  hypometh_Gplus_analysis,
  hypometh_Gminus_analysis
){

  ## If user has not supplied the final '/' in the TENET directory
  ## add it:
  TENET_directory <- ifelse(
    substring(
      TENET_directory,
      nchar(TENET_directory),
      nchar(TENET_directory)
    ) == '/',
    TENET_directory,
    paste(
      TENET_directory,
      '/',
      sep=''
    )
  )

  ## Create a step6 directory to deposit the output the tabulation files:
  dir.create(
    paste(
      TENET_directory,
      'step6/',
      sep=''
    )
  )

  ## Get the dataset of gencode v22 genes:
  gencode_v22_gtf <- TENETR.data::gencode_v22_annotations

  ## Get the gene annotations only:
  gencode_v22_genes <- gencode_v22_gtf[
    gencode_v22_gtf$type=='gene',
  ]

  rownames(gencode_v22_genes) <- sub(
    '\\..*',
    '',
    gencode_v22_genes$gene_id
  )

  ## Get the TR only info:
  TR_dataset <- TENETR.data::human_transcription_factors_dataset

  ## Get the accepted TRs out of the set:
  TR_gene_ID <- TR_dataset[
    TR_dataset$Is.TF.=='Yes',
    'Ensembl.ID'
  ]

  ## Generate results for hypermeth Gplus probes:
  if(hypermeth_Gplus_analysis==TRUE){

    ## Check that the hyper_Gplus_sig_link_zscores_perm_optimized.txt file exists;
    if(
      file.exists(
        paste(
          TENET_directory,
          'step5/',
          'hyper_Gplus_sig_link_zscores_perm_optimized.txt',
          sep=''
        )
      )
    ){

      ## Load the sig_link_zscores_perm_optimized.txt file for hypermeth Gplus
      ## generated by step5 optimize_links function:
      hypermeth_Gplus_sig_links <- read.delim(
        paste(
          TENET_directory,
          'step5/',
          'hyper_Gplus_sig_link_zscores_perm_optimized.txt',
          sep=''
        ),
        sep='\t',
        stringsAsFactors = FALSE
      )

    } else{

      ## Return an error message that the file wasn't found:
      stop('hyper_Gplus_sig_link_zscores_perm_optimized.txt in step5 of TENET directory was not found. Please check that the file exists and consider rerunning the step5 optimize_links function.')
    }

    ## Create a table dataset from this file:
    hypermeth_Gplus_all_gene_dataset <- as.data.frame(
      table(
        hypermeth_Gplus_sig_links$geneID
      ),
      stringsAsFactors=FALSE
    )

    ## Rename the columns:
    colnames(hypermeth_Gplus_all_gene_dataset) <- c(
      'geneID',
      'Freq'
    )

    ## Add the gene names to the dataset:
    hypermeth_Gplus_all_gene_dataset$geneSymbol <- gencode_v22_genes[
      hypermeth_Gplus_all_gene_dataset$geneID,
      'gene_name'
    ]

    ## Sort the data frame by decreasing number of links:
    hypermeth_Gplus_all_gene_dataset <- hypermeth_Gplus_all_gene_dataset[
      order(
        hypermeth_Gplus_all_gene_dataset$Freq,
        decreasing = TRUE
      ),
    ]

    ## Save that dataset as the all genes dataset:
    write.table(
      hypermeth_Gplus_all_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hyper_Gplus_links_all_gene_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )

    ## Now get only the TRs from this table:
    hypermeth_Gplus_TR_gene_dataset <- hypermeth_Gplus_all_gene_dataset[
      hypermeth_Gplus_all_gene_dataset$geneID %in% TR_gene_ID,
    ]

    ## Save that dataset as TR only dataset:
    write.table(
      hypermeth_Gplus_TR_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hyper_Gplus_links_all_TR_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )
  }

  ## Generate results for hypermeth Gplus probes:
  if(hypermeth_Gminus_analysis==TRUE){

    ## Check that the hyper_Gminus_sig_link_zscores_perm_optimized.txt file exists;
    if(
      file.exists(
        paste(
          TENET_directory,
          'step5/',
          'hyper_Gminus_sig_link_zscores_perm_optimized.txt',
          sep=''
        )
      )
    ){

      ## Load the sig_link_zscores_perm_optimized.txt file for hypermeth Gminus
      ## generated by step5 optimize_links function:
      hypermeth_Gminus_sig_links <- read.delim(
        paste(
          TENET_directory,
          'step5/',
          'hyper_Gminus_sig_link_zscores_perm_optimized.txt',
          sep=''
        ),
        sep='\t',
        stringsAsFactors = FALSE
      )

    } else{

      ## Return an error message that the file wasn't found:
      stop('hyper_Gminus_sig_link_zscores_perm_optimized.txt in step5 of TENET directory was not found. Please check that the file exists and consider rerunning the step5 optimize_links function.')
    }

    ## Create a table dataset from this file:
    hypermeth_Gminus_all_gene_dataset <- as.data.frame(
      table(
        hypermeth_Gminus_sig_links$geneID
      ),
      stringsAsFactors=FALSE
    )

    ## Rename the columns:
    colnames(hypermeth_Gminus_all_gene_dataset) <- c(
      'geneID',
      'Freq'
    )

    ## Add the gene names to the dataset:
    hypermeth_Gminus_all_gene_dataset$geneSymbol <- gencode_v22_genes[
      hypermeth_Gminus_all_gene_dataset$geneID,
      'gene_name'
    ]

    ## Sort the data frame by decreasing number of links:
    hypermeth_Gminus_all_gene_dataset <- hypermeth_Gminus_all_gene_dataset[
      order(
        hypermeth_Gminus_all_gene_dataset$Freq,
        decreasing = TRUE
      ),
    ]

    ## Save that dataset as the all genes dataset:
    write.table(
      hypermeth_Gminus_all_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hyper_Gminus_links_all_gene_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )

    ## Now get only the TRs from this table:
    hypermeth_Gminus_TR_gene_dataset <- hypermeth_Gminus_all_gene_dataset[
      hypermeth_Gminus_all_gene_dataset$geneID %in% TR_gene_ID,
    ]

    ## Save that dataset as TR only dataset:
    write.table(
      hypermeth_Gminus_TR_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hyper_Gminus_links_all_TR_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )
  }

  ## Generate results for hypometh Gplus probes:
  if(hypometh_Gplus_analysis==TRUE){

    ## Check that the hypo_Gplus_sig_link_zscores_perm_optimized.txt file exists;
    if(
      file.exists(
        paste(
          TENET_directory,
          'step5/',
          'hypo_Gplus_sig_link_zscores_perm_optimized.txt',
          sep=''
        )
      )
    ){

      ## Load the sig_link_zscores_perm_optimized.txt file for hypometh Gplus
      ## generated by step5 optimize_links function:
      hypometh_Gplus_sig_links <- read.delim(
        paste(
          TENET_directory,
          'step5/',
          'hypo_Gplus_sig_link_zscores_perm_optimized.txt',
          sep=''
        ),
        sep='\t',
        stringsAsFactors = FALSE
      )

    } else{

      ## Return an error message that the file wasn't found:
      stop('hypo_Gplus_sig_link_zscores_perm_optimized.txt in step5 of TENET directory was not found. Please check that the file exists and consider rerunning the step5 optimize_links function.')
    }

    ## Create a table dataset from this file:
    hypometh_Gplus_all_gene_dataset <- as.data.frame(
      table(
        hypometh_Gplus_sig_links$geneID
      ),
      stringsAsFactors=FALSE
    )

    ## Rename the columns:
    colnames(hypometh_Gplus_all_gene_dataset) <- c(
      'geneID',
      'Freq'
    )

    ## Add the gene names to the dataset:
    hypometh_Gplus_all_gene_dataset$geneSymbol <- gencode_v22_genes[
      hypometh_Gplus_all_gene_dataset$geneID,
      'gene_name'
    ]

    ## Sort the data frame by decreasing number of links:
    hypometh_Gplus_all_gene_dataset <- hypometh_Gplus_all_gene_dataset[
      order(
        hypometh_Gplus_all_gene_dataset$Freq,
        decreasing = TRUE
      ),
    ]

    ## Save that dataset as the all genes dataset:
    write.table(
      hypometh_Gplus_all_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hypo_Gplus_links_all_gene_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )

    ## Now get only the TRs from this table:
    hypometh_Gplus_TR_gene_dataset <- hypometh_Gplus_all_gene_dataset[
      hypometh_Gplus_all_gene_dataset$geneID %in% TR_gene_ID,
    ]

    ## Save that dataset as TR only dataset:
    write.table(
      hypometh_Gplus_TR_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hypo_Gplus_links_all_TR_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )
  }

  ## Generate results for hypometh Gplus probes:
  if(hypometh_Gminus_analysis==TRUE){

    ## Check that the hypo_Gminus_sig_link_zscores_perm_optimized.txt file exists;
    if(
      file.exists(
        paste(
          TENET_directory,
          'step5/',
          'hypo_Gminus_sig_link_zscores_perm_optimized.txt',
          sep=''
        )
      )
    ){

      ## Load the sig_link_zscores_perm_optimized.txt file for hypometh Gminus
      ## generated by step5 optimize_links function:
      hypometh_Gminus_sig_links <- read.delim(
        paste(
          TENET_directory,
          'step5/',
          'hypo_Gminus_sig_link_zscores_perm_optimized.txt',
          sep=''
        ),
        sep='\t',
        stringsAsFactors = FALSE
      )

    } else{

      ## Return an error message that the file wasn't found:
      stop('hypo_Gminus_sig_link_zscores_perm_optimized.txt in step5 of TENET directory was not found. Please check that the file exists and consider rerunning the step5 optimize_links function.')
    }

    ## Create a table dataset from this file:
    hypometh_Gminus_all_gene_dataset <- as.data.frame(
      table(
        hypometh_Gminus_sig_links$geneID
      ),
      stringsAsFactors=FALSE
    )

    ## Rename the columns:
    colnames(hypometh_Gminus_all_gene_dataset) <- c(
      'geneID',
      'Freq'
    )

    ## Add the gene names to the dataset:
    hypometh_Gminus_all_gene_dataset$geneSymbol <- gencode_v22_genes[
      hypometh_Gminus_all_gene_dataset$geneID,
      'gene_name'
    ]

    ## Sort the data frame by decreasing number of links:
    hypometh_Gminus_all_gene_dataset <- hypometh_Gminus_all_gene_dataset[
      order(
        hypometh_Gminus_all_gene_dataset$Freq,
        decreasing = TRUE
      ),
    ]

    ## Save that dataset as the all genes dataset:
    write.table(
      hypometh_Gminus_all_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hypo_Gminus_links_all_gene_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )

    ## Now get only the TRs from this table:
    hypometh_Gminus_TR_gene_dataset <- hypometh_Gminus_all_gene_dataset[
      hypometh_Gminus_all_gene_dataset$geneID %in% TR_gene_ID,
    ]

    ## Save that dataset as TR only dataset:
    write.table(
      hypometh_Gminus_TR_gene_dataset,
      file= paste(
        TENET_directory,
        'step6/',
        'hypo_Gminus_links_all_TR_freq.txt',
        sep=''
      ),
      quote= FALSE,
      sep='\t',
      row.names = FALSE
    )
  }
}
